rules:
  type-empty:
    - 2
    - never
  type-case:
    - 2
    - always
    - lower-case
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - test
      - refactor
      - style
      - build
      - ci
      - chore
      - perf
      - security
  subject-empty:
    - 2
    - never
  header-max-length:
    - 2
    - always
    - 100
