CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX ux_categories_name_ci
ON categories (lower(name));
