CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    category_id BIGINT NOT NULL,
    text VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_questions_category
        FOREIGN KEY (category_id) REFERENCES categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_questions_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE answer_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    question_id BIGINT NOT NULL,
    text VARCHAR(500) NOT NULL,
    correct BOOLEAN NOT NULL,
    display_order INT NOT NULL,

    CONSTRAINT fk_answer_options_question
        FOREIGN KEY (question_id) REFERENCES questions(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_answer_options_question_order
        UNIQUE (question_id, display_order),

    CONSTRAINT ck_answer_options_display_order
        CHECK (display_order > 0)
);

CREATE UNIQUE INDEX ux_answer_options_one_correct_per_question
ON answer_options(question_id)
WHERE correct = true;
