CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    category_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    duration_minutes INT NOT NULL,
    status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_quizzes_category
        FOREIGN KEY (category_id) REFERENCES categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_quizzes_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),

    CONSTRAINT ck_quizzes_duration
        CHECK (duration_minutes BETWEEN 1 AND 180)
);

CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    quiz_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    display_order INT NOT NULL,

    CONSTRAINT fk_quiz_questions_quiz
        FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_quiz_questions_question
        FOREIGN KEY (question_id) REFERENCES questions(id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_quiz_questions_quiz_question
        UNIQUE (quiz_id, question_id),

    CONSTRAINT uk_quiz_questions_quiz_order
        UNIQUE (quiz_id, display_order),

    CONSTRAINT ck_quiz_questions_display_order
        CHECK (display_order > 0)
);
