CREATE TABLE quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    quiz_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    quiz_title_snapshot VARCHAR(150) NOT NULL,
    category_id_snapshot BIGINT NOT NULL,
    category_name_snapshot VARCHAR(80) NOT NULL,
    duration_minutes INT NOT NULL,

    started_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    submitted_at TIMESTAMPTZ,
    abandoned_at TIMESTAMPTZ,

    status VARCHAR(30) NOT NULL,
    completion_reason VARCHAR(30),

    total_questions INT NOT NULL,
    correct_count INT NOT NULL,
    wrong_count INT NOT NULL,
    unanswered_count INT NOT NULL,
    score_percentage INT NOT NULL,
    scoring_version VARCHAR(30) NOT NULL,

    CONSTRAINT fk_quiz_attempts_quiz
        FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_quiz_attempts_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_quiz_attempts_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),

    CONSTRAINT ck_quiz_attempts_completion_reason
        CHECK (
            completion_reason IS NULL
            OR completion_reason IN ('MANUAL', 'TIME_EXPIRED')
        ),

    CONSTRAINT ck_quiz_attempts_duration
        CHECK (duration_minutes BETWEEN 1 AND 180),

    CONSTRAINT ck_quiz_attempts_score
        CHECK (score_percentage BETWEEN 0 AND 100),

    CONSTRAINT ck_quiz_attempts_counts
        CHECK (
            total_questions > 0
            AND correct_count >= 0
            AND wrong_count >= 0
            AND unanswered_count >= 0
            AND correct_count + wrong_count + unanswered_count = total_questions
        ),

    CONSTRAINT ck_quiz_attempts_time
        CHECK (expires_at > started_at),

    CONSTRAINT ck_quiz_attempts_lifecycle
        CHECK (
            (
                status = 'IN_PROGRESS'
                AND submitted_at IS NULL
                AND abandoned_at IS NULL
                AND completion_reason IS NULL
            )
            OR (
                status = 'COMPLETED'
                AND submitted_at IS NOT NULL
                AND abandoned_at IS NULL
                AND completion_reason IS NOT NULL
            )
            OR (
                status = 'ABANDONED'
                AND submitted_at IS NULL
                AND abandoned_at IS NOT NULL
                AND completion_reason IS NULL
            )
        )
);

CREATE UNIQUE INDEX uq_quiz_attempts_active_user_quiz
ON quiz_attempts(user_id, quiz_id)
WHERE status = 'IN_PROGRESS';

CREATE TABLE attempt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    attempt_id BIGINT NOT NULL,
    original_question_id BIGINT,
    question_text VARCHAR(1000) NOT NULL,
    display_order INT NOT NULL,
    selected_option_id BIGINT,
    answer_revision INT NOT NULL DEFAULT 0,
    answered_at TIMESTAMPTZ,
    correct BOOLEAN,

    CONSTRAINT fk_attempt_questions_attempt
        FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_attempt_questions_attempt_order
        UNIQUE (attempt_id, display_order),

    CONSTRAINT ck_attempt_questions_display_order
        CHECK (display_order > 0)
);

CREATE TABLE attempt_answer_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    attempt_question_id BIGINT NOT NULL,
    original_answer_option_id BIGINT,
    option_text VARCHAR(500) NOT NULL,
    correct BOOLEAN NOT NULL,
    display_order INT NOT NULL,

    CONSTRAINT fk_attempt_answer_options_question
        FOREIGN KEY (attempt_question_id) REFERENCES attempt_questions(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_attempt_answer_options_question_order
        UNIQUE (attempt_question_id, display_order),

    CONSTRAINT ck_attempt_answer_options_display_order
        CHECK (display_order > 0)
);

CREATE UNIQUE INDEX ux_attempt_options_one_correct_per_question
ON attempt_answer_options(attempt_question_id)
WHERE correct = true;
